services:

  pg_db:
    image: postgres:latest
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

    networks:
      - backend

  server:
    build: server/
    image: musictechserver
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - pgadmindata:/var/lib/server
    #command: bash -c 'do sleep 1; done;'
    depends_on:
      - pg_db
    networks:
      - backend
      - frontend


  client:
    build: client/musictech-client/
    image: musictechclient

    ports:
      - 4200:80
    expose:
      - 4200
    volumes:
      - pgadmindata:/var/lib/client
    depends_on:
      - server
    networks:
      - frontend

networks:
  frontend:
  backend:


volumes:
  pgdata:
  pgadmindata:


